---
argument_specs:
  main:
    version_added: 2.0.0
    short_description: A role to Create/Delete/Configure an Azure Network Interface.
    description:
      - A role to Create/Delete/Configure an Azure Network Interface.
      - This role requires an azure user account with valid permission.
    options:
      azure_manage_network_interface_operation:
        description:
          - Operation to perform
        default: "create"
        choices: ["create", "delete"]
      azure_manage_network_interface_resource_group:
        description:
          - Resource group.
        required: true
      azure_manage_network_interface_interface:
        description:
          - Object used to provide details for a network interface.
        type: dict
        options:
          name:
            description: Name of the network interface.
            required: true
          vnet_name:
            description:
              - Name of the existing azure virtual network where the network interface will reside.
              - Required when O(azure_manage_network_interface_operation=create).
          subnet_name:
            description:
              - Name of the existing azure subnet where the network interface will reside.
              - Required when O(azure_manage_network_interface_operation=create).
          security_group_name:
            description:
              - Name of the existing security group with which to associate the network interface.
              - If not provided, a default security group will be created when O(create_with_security_group=true).
          create_with_security_group:
            description: Whether or not a default security group should be created with the network interface.
            type: bool
            default: true
          os_type:
            description:
              - Determines any rules to be added to a network interface's default security group.
              - If O(os_type=Windows), a rule allowing RDP access will be added.
              - If O(os_type=Linux), a rule allowing SSH access will be added.
          enable_accelerated_networking:
            description: Set to V(yes) to enable accelerated networking.
            type: bool
          ip_forwarding:
            description: Set to V(yes) to enable ip forwarding.
            type: bool
          dns_servers:
            description: List of IP addresses representing which DNS servers the network interface should look up.
            type: list
          ip_configurations:
            description: List of IP configurations.
            type: list
            elements: dict
            options:
              name:
                description: Name of the IP configuration.
                required: true
              primary:
                description:
                  - Set to V(yes) to make IP configuration the primary one.
                  - The first IP configuration is by default set to O(primary=yes).
              application_security_groups:
                description: List of application security groups in which the IP configuration is included.
                type: list
                elements: str
              load_balancer_backend_address_pools:
                description: List of existing load balancer backend address pools in which the network interface will be load balanced.
                type: list
                elements: str
              private_ip_address:
                description: Private IP address for the IP configuration.
              private_ip_address_version:
                description: Ip version.
                default: 'IPv4'
                choices: ['IPv4', 'IPv6']
              private_ip_allocation_method:
                description: Ip allocation method.
                default: 'Dynamic'
                choices: ['Dynamic', 'Static']
              public_ip_address_name:
                description: Name of the existing public IP address to be assigned to the network interface.
              public_ip_allocation_method:
                description: Ip allocation method.
                default: 'Dynamic'
                choices: ['Dynamic', 'Static']
          tags:
            description: Metadata for the network interface.
            type: dict
