---
galaxy_info:
  author: Bikouo Aubin
  description: Role to manage network interface in Azure Cloud.
  company: Red Hat

  license: GPL-3.0-or-later

  min_ansible_version: 2.15.0

  platforms:
    - name: EL
      versions:
        - "8"

  galaxy_tags:
    - linux
    - system
    - ansible

dependencies: []
collections:
  - azure.azcollection
...
