---
- name: Get server info
  azure.azcollection.azure_rm_postgresqlserver_info:
    resource_group: "{{ azure_manage_postgresql_resource_group }}"
    name: "{{ azure_manage_postgresql_postgresql_name }}"
  register: server_info

- name: Get Resource group info
  azure.azcollection.azure_rm_resourcegroup_info:
    name: "{{ azure_manage_postgresql_resource_group }}"
  register: rg_info

- name: Create or delete Azure PostgreSQL server
  ansible.builtin.include_tasks: "{{ azure_manage_postgresql_operation }}.yml"
